#!/usr/bin/env bash
# vim: ft=bash :

SOURCE="$(chezmoi source-path)"
WATCH_SCRIPT="${SOURCE}/.bin/apply"

if watchman watch-list | grep -q "$SOURCE"; then
	echo "Watchman is currently active for this repository."
	echo "Do you want to stop the service? (y/n)"
	read -n 1 -r

	if [[ $REPLY =~ ^[Yy]$ ]]; then
		watchman watch-del "$SOURCE" > /dev/null
		echo -e "\nWatchman service stopped."
	fi

	exit 0
fi

watchman watch "${SOURCE}"

watchman -j <<EOT
["trigger", "${SOURCE}", {
  "name": "chezmoi-auto-apply",
  "append_files": false,
  "command": ["${WATCH_SCRIPT}"]
}]
EOT

if [ -z "$TMUX" ]; then
	echo "WARNING: tmux not detected."
	echo "Changes requiring user intervention to apply might hang Watchman."
fi

echo "Watchman is now watching $SOURCE."
echo "Changes will be immediately reflected in your user configurations."
echo "To stop Watchman, run this script again."
